### ISSUE TITLE
运行后提示  dialogs 无法进行迭代操作

### ISSUE THREAD

**Issue by josways** [yeziyezi/scripts#1]
![image](https://user-images.githubusercontent.com/30266923/56344515-345bfd80-61f0-11e9-8937-9544c464e0a9.png)

**Comment by escyezi** [comment]
感谢提交bug，正在处理中

**Comment by josways** [comment]
> 感谢提交bug，正在处理中

我已修改成功，Pull Requests 合并一下即可。

**Comment by escyezi** [comment]
你的PR我已经看过，存在一点小错误，而且在readme和注释中添加了过多内容，所以决定不予合并。感谢支持。
