### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by SplitGemini** [yeziyezi/scripts#5]
![image](https://user-images.githubusercontent.com/34861918/102997975-3350a700-4561-11eb-8d41-26ff91200bfe.png)

关于代理，python>=3.6需要更改逻辑

[https://docs.telethon.dev/en/latest/basic/signing-in.html#signing-in](https://docs.telethon.dev/en/latest/basic/signing-in.html#signing-in)

**Comment by escyezi** [comment]
谢谢，已合并
